server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true                    # \u662F\u5426\u6839\u636E\u670D\u52A1id\u5EFA\u7ACB\u8DEF\u7531
          lower-case-service-id: true      # \u662F\u5426\u4F7F\u7528\u5C0F\u5199\u670D\u52A1id
      routes:
      - id: eureka-server
        uri: lb://eureka-server            # uri\u4EE5lb://\u5F00\u5934\uFF08lb\u4EE3\u8868\u4ECE\u6CE8\u518C\u4E2D\u5FC3\u83B7\u53D6\u670D\u52A1\uFF09\uFF0C\u540E\u9762\u63A5\u7684\u5C31\u662F\u4F60\u9700\u8981\u8F6C\u53D1\u5230\u7684\u670D\u52A1\u540D\u79F0
        predicates:
        - Path=/eureka/**



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

