server:
  port: 8888

spring:
  application:
    name: redis-server
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000ms

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
